# --------------------- Install Python on the Raspberry Pi ---------------------

# Install Python
sudo apt install python3 python3-pip

# Install a library needed for the inference server
sudo apt-get install -y libgl1

# Select the env
conda env list
conda activate python-inference-env

# Start the app
uvicorn app:app --host 0.0.0.0 --port 3002